baseURL: 'https://leslietang.com/'
languageCode: 'en-us'
title: 'Leslie Tang'
theme: 'hugo-PaperMod'

params:
    googleAnalyticsID: G-3KGERJCSCY
    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
    profileMode:
      enabled: true
      title: Leslie TANG
      # imageUrl: "#"
      # imageTitle: my image
      # imageWidth: 120
      # imageHeight: 120
      subtitle: "my current writings are trials to find my content creation fit"
      buttons:
          - name: Writings
            url: posts
          - name: Resume
            url: "https://leslietang.com/files/resume_14Jan2022.pdf"

    # https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-icons/
    socialIcons:
        - name: LinkedIn
          url: "https://www.linkedin.com/in/leslie-tang/"
        - name: github
          url: "https://github.com/tangweejieleslie/"
        - name: email
          url: "mailto:tangweejieleslie+ghpages@gmail.com"
        # - name: dev
        #   url: "https://dev.to/tangweejieleslie"

menu:
    main:
        - name: archives
          url: /archives/
          weight: 10
        - name: search
          url: /search/
          weight: 10
        - name: categories
          url: /categories/
          weight: 10
        - name: tags
          url: /tags/
          weight: 20

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary