baseURL: 'https://leslietang.com/'
languageCode: 'en-us'
title: 'Leslie Tang'
theme: 'hugo-PaperMod'

params:
    googleAnalyticsID: G-3KGERJCSCY
    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

menu:
    main:
        - name: archives
          url: /archives/
          weight: 10
        - name: search
          url: /search/
          weight: 10
        - name: categories
          url: /categories/
          weight: 10
        - name: tags
          url: /tags/
          weight: 20

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary