baseURL = "https://leslietang.com"
title = "Leslie TANG"
paginate = 5
theme = "hugo-PaperMod"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = true
buildFuture = false
buildExpired = false
enableEmoji = true
googleAnalytics = "UA-140833487-1"

[minify]
disableXML = true

[[menu.main]]
name = "Archives"
url = "archives"
weight = 5

[[menu.main]]
name = "Search"
url = "search/"
weight = 10

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[[menu.main]]
name = "Categories"
url = "categories/"
weight = 10

# [[languages.en.menu.main]]
# name = "Timeline"
# url = "https://timeline.leslietang.com/"
# weight = 10
# [[languages.en.menu.main]]
# name = "Drafts"
# url = "drafts/"
# weight = 10


[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "Leslie Tang"
author = "Leslie Tang"
defaultTheme = "auto"
ShowShareButtons = false
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true
images = [ "papermod-cover.png" ]

  [params.profileMode]
  enabled = false
  title = "Leslie TANG"
  imageUrl = "#"
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Leslie Tang"
  Content = """
  Welcome to my website! This is still a work in progress.
  """

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/tangweejieleslie/leslietang.com"

  [[params.socialIcons]]
  name = "polywork"
  url = "https://timeline.leslietang.com/"

  

  # [[params.socialIcons]]
  # name = "KoFi"
  # url = "https://ko-fi.com/adityatelange"

  # [[params.socialIcons]]
  # name = "RsS"
  # url = "index.xml"

  [params.editPost]
  URL = "https://github.com/tangweejieleslie/leslietang.com/tree/experiment/working_folder/content"
  Text = "Suggest Changes"
  appendFilePath = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# [markup.goldmark.renderer]
# unsafe = true

# [privacy.vimeo]
# disabled = false
# simple = true

# [privacy.twitter]
# disabled = false
# enableDNT = true
# simple = true

# [privacy.instagram]
# disabled = false
# simple = true

# [privacy.youtube]
# disabled = false
# privacyEnhanced = true

# [services.instagram]
# disableInlineCSS = true

# [services.twitter]
# disableInlineCSS = true
