baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Leslie Tang"
theme = "hugo-PaperMod"
disqusShortname = "hugo-PaperMod"
googleAnalytics = "UA-140833487-1"
paginate = 7
canonifyurls = true


[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowBreadCrumbs = true

  [params.profileMode]
  enabled = true
  title = "Leslie TANG"
  subtitle = "my personal website"

    [[params.profileMode.buttons]]
    name = "Archive"
    url = "/archive"

    [[params.profileMode.buttons]]
    name = "Github"
    url = "https://github.com/tangweejieleslie/"

  [[params.socialIcons]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/leslie-tang/"

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

  [params.editPost]
  URL = "https://github.com/tangweejieleslie/leslietang.com/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.outputs]
  home = [ "HTML", "RSS", "JSON" ]

[cover]
image = "<image path/url>"
alt = "<alt text>"
caption = "<text>"
relative = false
