# mainSections = ["post", "posts"] # Default to ["posts"].

# titleSeparator = "|" # Title separator. Default to "-".

description = "Leslie Tang's personal website. Contains my thoughts, works, projects, and other things."
keywords = "Leslie Tang, Software Engineer, Software Quality Assurance, Game Developer, Indie, Freelancer"
# images = ["site-feature-image.jpg"]

metaRobots = "noindex, nofollow" # Default value for Meta Tag "robots"
# metaRobots = "" # disable Meta Tag "robots"

# logo = "images/logo.png" # Logo image. Default to "images/logo.webp".
logo = false # Disable Logo
brand = "Leslie TANG"

palette = "bluegray" # Default palette. Optional.
# palettes = ["blue", "blue gray", "brown"] # Available palettes. Default to ALL.
# palettes = ["bluegray"] # Disable palette switcher.
# palettes = []

# color = "dark" # light, dark or dynamic. Default to dynamic.
# color = "#132235"

# fullWidth = true # Full width.
# fixedHeader = false # Turn on/off fixed header.

# dateFormat = "Jan 2, 2006"

# Google Adsense
googleAdsense = ""

# math = true # Enable math globally.
# toc = true # Disable TOC globally.
# breadcrumb = false # Disable breadcrumb
# diagram = true
# socialShare = false # disable social network sharing
# searchBar = false # disable search-bar

# poweredBy = false # Whether to show powered by.

# readingTime = false # Whether to display the reading time.
# readingTime = false
# postDate = false # Whether to display the post date in the post meta section.

# featuredPostCount = 10 # The number of featured posts shown in sidebar. Turn off by setting it to false.
# recentPostCount = 10 # The number of recent posts shown in sidebar. Turn off by setting it to false.
# relatedPostCount = 10 # The number of related posts. Turn off by setting it to false.
# categoryCount = 10 # The number of categories shown in sidebar. Turn off by setting it to false.
# tagCount = 10 # The number of tags shown in sidebar. Turn off by setting it to false.
# seriesCount = 10 # The number of series shown in sidebar. Turn off by setting it to false.
taxonomyPaginate = 5 # Default to 10.
# taxonomyPostCount = 5 # The number of posts of taxonomy. Turn off by setting it to false.

# Custom CSS and JS
customCSS = [
]
customJS = [
]

# tocWordCount = 280 # TOC is displayed only if the post's word count exceeds this value.

titleCase = true # Capitalized title.

viewer = true # Image Viewer

[codeBlock]
  # maxLines = 8
  lineNos = false # true/false represents that show/hide the line numbers by default.

[post]
  # excerpt = "description"
  # excerptMaxLength = 120

[archive]
  paginate = 8 # Archive pagination. Default to 100.
  # dateFormat = "01-02" # Archive date format. Default to "Jan 2".

# [analytics]
  # baidu = "" # Baidu Analytics

# Site verification
# [siteVerification]
#   google = ""
#   bing = ""
#   baidu = ""
#   baiduUnion = "" # Baidu Union
#   so = ""
#   sogou = ""
#   shenma = ""

# [creativeCommons]
  # by = true # Credit must be given to you, the creator.
  # nc = true # Only noncommercial use of your work is permitted.
  # nd = true # No derivatives or adaptations of your work are permitted.
  # sa = true # Adaptations must be shared under the same terms.

[utterances]
  repo = "tangweejieleslie/leslietang.com" # Replace with your repository.
  #issueTerm = "pathname" # pathname, url, title, og:title
  #label = "comment"
  # By default, light and dark mode correspond to github-light and github-dark, respectively.
  # Optional values: github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.
  #theme = "" 

[search]
  paginate = 5 # Pagination. Default to 10.
  # resultContentWordCount = 240 # The maximum word count of result content for displaying.
  # Fuse.js options. See https://fusejs.io/api/options.html.
  [search.fuse]
    # ignoreLocation = true
    # location = 0
    # isCaseSensitive = false
    # minMatchCharLength = 1
    threshold = 0.1
    # distance = 100
    # useExtendedSearch = true

# [reward]
  # alipay = "images/reward/alipay.png"
  # wechat = "images/reward/wechat.png"
  #paypal = "images/reward/paypal.png"
  #patreon = "images/reward/patreon.png"
  #liberapay = "images/reward/liberapay.png"

#[share]
  #addThis = "" # AddThis pubid.

[fontSize] # Comment or remove this settings to disable font size switcher.
  # extraSmall = ".8rem"
  # small = ".9rem"
  # large = "1.1rem"
  # extraLarge = "1.2rem"

[pwa]
  [pwa.manifest]
    # name = "" # Default to site title.
    short_name = "LT"
    # display = "fullscreen" # Default to standalone.
    # description = "" # Default to site description.
    # theme_color = ""
    # background_color = ""

    # Icons
    # [[pwa.manifest.icons]]
    #   sizes = "96x96"
    #   src = "/images/icons/icon-96x96.png"
    # [[pwa.manifest.icons]]
    #   sizes = "144x144"
    #   src = "/images/icons/icon-144x144.png"

[contact]
  endpoint = "https://getform.io/f/9fa47ced-6cc4-4884-aada-2b1498887e8b" # Backend endpoint, remove this line if you're using Netlify.
